<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ss</string>
	</array>
	<key>name</key>
	<string>SilverStripe</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#include</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#conditional</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single_control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single_var</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#i18n</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#partial_caching</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#html_tags</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#css</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#javascript</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;%\-\-)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ss</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\-\-%&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ss</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.ss</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bad-comments-or-CDATA.ss</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>conditional</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;%\s)(else_if|if\snot|if)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.ss</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Conditional stements (if/if_else/if not)</string>
					<key>end</key>
					<string>(\s*%&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.ss.embedded.conditional</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(=|!=|&amp;&amp;|\|)</string>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([a-zA-Z0-9_\(\)\$"])</string>
							<key>name</key>
							<string>variable.parameter.ss</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>css</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:style))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.style.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)((?i:style))(&gt;)(?:\s*\n)?</string>
			<key>name</key>
			<string>source.css.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=&lt;/(?i:style))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>html_tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;!--)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(--&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.</string>
						</dict>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bad-comments-or-CDATA.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;)([a-zA-Z0-9:]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)(&lt;)(/)(\2)(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html meta.scope.between-tag-pair.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.html</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:body|head|html)\b)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.structure.any.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.structure.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:address|blockquote|dd|div|dl|dt|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|hr|menu|pre)\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.block.any.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.block.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)((?i:a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\b)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.inline.any.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>((?: ?/)?&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.inline.any.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;/?)([!a-zA-Z0-9:]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.other.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.other.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_stuff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;&gt;</string>
					<key>name</key>
					<string>invalid.illegal.incomplete.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;</string>
					<key>name</key>
					<string>invalid.illegal.bad-angle-bracket.html</string>
				</dict>
			</array>
		</dict>
		<key>i18n</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.ss</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Translatable text tags</string>
					<key>match</key>
					<string>(&lt;%t)(.*)(\s%&gt;)</string>
					<key>name</key>
					<string>source.ss.embedded.i18n</string>
				</dict>
			</array>
		</dict>
		<key>include</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;%)\s+(include)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.ss</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(%&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.ss.embedded.include</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.ss</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([a-zA-Z0-9_\.=]*)</string>
							<key>name</key>
							<string>variable.parameter.ss</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#single_var</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>javascript</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=&lt;/(script|SCRIPT))(&gt;)(?:\s*\n)?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.js.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:script|SCRIPT))(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.script.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)((?i:script))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.js</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(//).*?((?=&lt;/script)|$\n?)</string>
							<key>name</key>
							<string>comment.line.double-slash.js</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>/\*</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.js</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\*/|(?=&lt;/script)</string>
							<key>name</key>
							<string>comment.block.js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#php</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>partial_caching</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.ss</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.ss</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.ss</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Special partial caching syntax</string>
					<key>match</key>
					<string>(&lt;%\s)(cacheblock|cached)\s?('[a-zA-Z0-9]*?')?\s?(,\s?[a-zA-Z0-9]*?)?(\s%&gt;)</string>
					<key>name</key>
					<string>source.ss.embedded.block</string>
				</dict>
			</array>
		</dict>
		<key>single_control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.ss</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.ss</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant.ss</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Single control keywords</string>
					<key>match</key>
					<string>(&lt;%\s)(else|end_if|control|end_control|with|end_with|Loop|end_Loop|loop|end_loop|base_tag|require|cacheblock|end_cacheblock|cached|end_cached|uncached|end_uncached)(.*)(\s%&gt;)</string>
					<key>name</key>
					<string>source.ss.embedded.block</string>
				</dict>
			</array>
		</dict>
		<key>single_var</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>SS custom Variables</string>
					<key>match</key>
					<string>(\{)?(\$)([a-zA-Z0-9\._]*)(\(?)([a-zA-Z0-9_\-,\s]*)?(\)?)(\})?</string>
					<key>name</key>
					<string>variable.parameter.ss</string>
				</dict>
			</array>
		</dict>
		<key>string_double_quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_var</string>
				</dict>
			</array>
		</dict>
		<key>string_single_quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_var</string>
				</dict>
			</array>
		</dict>
		<key>tag_generic_attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z\-:]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#conditional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_control</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_var</string>
				</dict>
			</array>
		</dict>
		<key>tag_id_attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=''|")</string>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#partial_and_var</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#include</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#conditional</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#single_control</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#single_var</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag_stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_id_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_generic_attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_double_quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single_quoted</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.ss</string>
	<key>uuid</key>
	<string>9b9e9065-622f-479d-82f1-6c403382e932</string>
</dict>
</plist>
